site_name: Workspace Tab Manager
site_url: https://torynet.github.io/opera-workspace-tab-manager/
repo_url: https://github.com/torynet/opera-workspace-tab-manager
repo_name: torynet/opera-workspace-tab-manager
theme:
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - navigation.indexes
    - navigation.top
    - navigation.path
    - navigation.tracking
    - navigation.instant
    - search.highlight
    - toc.follow
    - content.code.copy
  toc_depth: 3

markdown_extensions:
  - toc:
      permalink: true    # Add anchors to headings
  - admonition
  - attr_list
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format

extra_javascript:
  - https://unpkg.com/mermaid@10/dist/mermaid.min.js

nav:
  - Home: index.md
  - User Guide:
      - Installation & Configuration: config.md
      - Usage Guide: usage.md
      - Privacy Policy: privacy.md
      - License: license.md
  - Development Guide:
      - Overview: development/index.md
      - Architecture: development/architecture.md
      - Flow Diagrams: development/diagrams.md
      - Documentation Guide: development/documentation.md
      - Contribution Guidelines: development/contributing.md
      - Maintenance Guide: development/maintenance.md
      - Publishing Guide: development/publishing.md
