name: 'Version Utils'
description: 'Common version manipulation functions'

inputs:
  tag:
    description: 'Git tag to parse'
    required: true
  increment:
    description: 'Calculate next version (none|rc|release)'
    required: false
    default: 'none'
  force_version:
    description: 'Force specific version (overrides increment)'
    required: false

outputs:
  version:
    description: 'Version without v prefix'
    value: ${{ steps.parse.outputs.version }}
  is_rc:
    description: 'True if version is RC'
    value: ${{ steps.parse.outputs.is_rc }}
  is_release:
    description: 'True if version is release'
    value: ${{ steps.parse.outputs.is_release }}
  next_version:
    description: 'Next version if increment specified'
    value: ${{ steps.parse.outputs.next_version }}

runs:
  using: composite
  steps:
    - uses: ./.github/actions/constants
      id: constants

    - id: parse
      shell: bash
      run: |
        if [[ "${{ inputs.tag }}" == refs/* ]] || [[ -z "${{ inputs.tag }}" ]]; then
          TAG=$(git tag -l 'v*' --sort=-v:refname | while read tag; do
            if [[ $tag =~ ${{ steps.constants.outputs.version_pattern }} ]]; then
              echo $tag
              break
            fi
          done)
        else
          TAG="${{ inputs.tag }}"
        fi
        VERSION="${TAG#v}"

        # Parse version
        if [[ $TAG =~ ${{ steps.constants.outputs.version_pattern }} ]]; then
          MAJOR="${BASH_REMATCH[1]}"
          MINOR="${BASH_REMATCH[2]}"
          PATCH="${BASH_REMATCH[3]}"
          RC="${BASH_REMATCH[5]}"
          RELEASE="${BASH_REMATCH[6]}"

          echo "version=$VERSION" >> $GITHUB_OUTPUT

          if [[ $TAG =~ -rc ]]; then
            echo "is_rc=true" >> $GITHUB_OUTPUT
            echo "is_release=false" >> $GITHUB_OUTPUT
          elif [[ $TAG =~ -r ]]; then
            echo "is_rc=false" >> $GITHUB_OUTPUT
            echo "is_release=true" >> $GITHUB_OUTPUT
          else
            echo "is_rc=false" >> $GITHUB_OUTPUT
            echo "is_release=false" >> $GITHUB_OUTPUT
          fi

          # Calculate next version if requested
          if [ -n "${{ inputs.force_version }}" ]; then
            NEXT_VERSION="${{ inputs.force_version }}"

          elif [ "${{ inputs.increment }}" = "rc" ]; then
            if [ -n "$RC" ]; then
              # Increment RC number: 1.0.0-rc1 -> 1.0.0-rc2
              NEXT_VERSION="${MAJOR}.${MINOR}.${PATCH}-rc$(($RC + 1))"
            else
              # Start new RC series: 1.0.0 -> 1.1.0-rc1
              NEXT_VERSION="${MAJOR}.$(($MINOR + 1)).0-rc1"
            fi

          elif [ "${{ inputs.increment }}" = "release" ]; then
            if [ -n "$RC" ]; then
              # Convert RC to release: 1.0.0-rc2 -> 1.0.0-r
              NEXT_VERSION="${MAJOR}.${MINOR}.${PATCH}-r"
            else
              echo "Can only create release from RC version" >&2
              exit 1
            fi
          fi

          if [ -n "$NEXT_VERSION" ]; then
            echo "next_version=$NEXT_VERSION" >> $GITHUB_OUTPUT
          fi
        else
          echo "Invalid version format: $TAG" >&2
          exit 1
        fi
