name: Build Extension Package

permissions:
  contents: write

on:
  push:
    tags:
      - 'v*-rc*'  # Matches RC tags like v1.0.0-rc1
      - 'v*-r'    # Matches release tags like v1.0.0-r

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: ./.github/actions/version
        id: version
        with:
          tag: ${{ github.ref_name }}
          increment: none

      - uses: ./.github/actions/package
        id: package
        with:
          version: ${{ steps.version.outputs.version }}

      # Only create release when triggered by a tag push
      - name: Create release
        if: startsWith(github.ref, 'refs/tags/')
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release create ${{ github.ref_name }} \
            ${{ steps.package.outputs.package_name }} \
            --title "Version ${GITHUB_REF#refs/tags/v}" \
            --notes "Package build for ${{ github.ref_name }}" \
            ${{ steps.version.outputs.is_rc == 'true' && '--prerelease' || '' }}
