name: Validate pull request
on:
  pull_request:
    types: [opened, edited, synchronize, reopened]

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: Validate pull request
        uses: Namchee/conventional-pr@v0.15.6
        with:
          access_token: ${{ secrets.GITHUB_TOKEN }}
          title_pattern: "^(feature|patch|chore|docs|ci|test|refactor)(!)? #[0-9]+:.*"
          body: true
          issue: true
          maximum_changes: 0
          verbose: true
