name: Build Extension Package

on:
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Get version from tag
        id: get_version
        run: echo "VERSION=${GITHUB_REF#refs/tags/v}" >> $GITHUB_ENV

      - name: Validate manifest.json
        run: |
          # Check if manifest.json exists and is valid JSON
          if ! jq . manifest.json > /dev/null 2>&1; then
            echo "Error: manifest.json is not valid JSON"
            exit 1
          fi

          # Check if version matches tag
          MANIFEST_VERSION=$(jq -r .version manifest.json)
          if [ "$MANIFEST_VERSION" != "$VERSION" ]; then
            echo "Error: manifest.json version ($MANIFEST_VERSION) does not match tag version ($VERSION)"
            exit 1
          fi

      - name: Check required files
        run: |
          REQUIRED_FILES=("manifest.json" "popup.html" "popup.js" "background.js" "options.html" "options.js")
          for file in "${REQUIRED_FILES[@]}"; do
            if [ ! -f "$file" ]; then
              echo "Error: Required file $file is missing"
              exit 1
            fi
          done

          # Check if icons exist
          ICON_SIZES=("16" "48" "128")
          for size in "${ICON_SIZES[@]}"; do
            if [ ! -f "icons/icon${size}.png" ]; then
              echo "Error: Icon icons/icon${size}.png is missing"
              exit 1
            fi
          done

      - name: Create extension package
        run: |
          zip -r workspace-tab-manager-v$VERSION.zip . \
          -x "*.git*" \
          -x ".github/*" \
          -x ".editorconfig" \
          -x "PUBLISHING.md" \
          -x "*.md" \
          -x "metadata.json"

      - name: Upload to release
        run: |
          gh release upload ${{ github.ref_name }} \
            workspace-tab-manager-v$VERSION.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
